### PR TITLE
Update

### PR DESCRIPTION
**Pull request by devgabrielcoman**
Final changes in this PR:

Because KWS has unique Ids as `Ints` and PopJam as `Strings` 👎I made the `IUniqueIdentityTrait` protocol work on an `AnyHashable` data type rather than String or Int or anything else.

```
public protocol IUniqueIdentityTrait: ITrait {
    var id: AnyHashable { get set }
}
```

### CODE REVIEW

**Comment by Tbruni85** [comment]
I don't agree with this approach, as I raised my concern yesterday we can't create an interface or protocol per each object we receive.
That should be left to the Model to implement the object types it needs.
This will create a ridiculous, and to my opinion completely useless, chain of extensions.

It's up to the mapper to take care of the object type, if it's an Int or  a String, not to a protocol.

**Comment by devgabrielcoman** [comment]
I understand having 

```
public protocol IUniqueIdentityTrait: ITrait {}
public protocol IUniqueStringIdentityTrait: IUniqueIdentityTrait {
    var id: String { get set }
}
public protocol IUniqueIntIdentityTrait: IUniqueIdentityTrait {
    var id: Int { get set }
}
```

might not be the best code ever written. We can definitely improve on that, fore sure.

> We can't create an interface or protocol per each object we receive.
> That should be left to the Model to implement the object types it needs.

That's what we're trying to do here, in the Protobufs library. Maybe not every model & stuff, some of them can be internal to PopJam or KWS, but the ones that we need for both UI & Data, those should be **defined as protocols here**.

**Comment by Tbruni85** [comment]
https://media.giphy.com/media/mxDZecDOOsWCA/giphy.gif


Only "main" Model should be defined by a protocol.
i.e. 

```
public protocol IModel {
    var id: String {get set}
}
```

so we force every Model conforming to it to implement an unique identifier.
But I don't agree with having protocols which implement specific parameters such as:


```
public protocol  IUserSocialDetailsModel: IMode,  IUniqueIdentityTrait, IUniqueNameTrait, IMultiLanguageTrait, IFollowedTrait, IFollowingTrait {
    val bio: String?
    val profileColour: Int?
    val isLoggedUser: Boolean
    val isStaff: Boolean
    val isPartner: Boolean
    val isPrivate: Boolean
    val isUltra: Boolean
    val isDummy: Boolean
    val joinedAt: Long
    val country: String?
    val postCount: Int
    val userLevel: Int
    val profileImage: IImageModel?
    val feedBackground: IImageModel?
    val profileBackground: IImageModel?
}
```

this one it's too specific.
We agreed on having generic basic protocols for the main models, now we're implementing a protocol for every type of response.

**Comment by devgabrielcoman** [comment]
Well going a little off topic to the purpose of this particular PR (it's just to add a few Trait-type interfaces):

1) If we have our IModel protocol like this:

```
public protocol IModel {
    var id: String {get set}
}
```
what happens to the Models that don't have any Id field? Like IValidationModel, IConfigModel, etc? They're forced to have a non-optional field that they have to fill in with an empty string. Or not implement the IModel protocol at all. 
 
2) If we just have very common definitions in Protobuf, like IModel and IService and that's about it, then we might as well not have Protobuf at all.
But, if we give up Protobuf, here's what we're left with:

PopJam-Data-SDK has its own models
KWS-Data-SDK has its own models
PopJam-UI has to depend on PopJam-Data-SDK directly.

Instead of **loosely coupling** SDKs by using the Protobufs library, we **tightly couple** them.

And that causes two problems: 
a) We can't work in parallel. At all. We have to finish work on the Data SDK and then move on the UI SDK. Using Protobufs, we just define what we need, have both Data & UI depend on it but not on each other and then I can work on the Data part, Stu can work on the UI, etc, all independent of one another. We do gain time and efficiency. 
b) We can't work to integrate KWS at all. KWS and PopJam won't have a common definitions base at all (provided by Protobufs). Which means that when we want to switch out PopJam Auth for KWS Auth **we basically have to re-write some code instead of switching one `IAuthService` implementation with another**. That's also wasted time and efficiency and kind of goes against the drive to unify those two things (which Josh et comp is really pushing for).  

Furthermore having a Protobufs library with well defined and completely defined models allows us to do this little thing:
Say we want to provide Auth (login / create) in both KWS and PopJam.

But we know that PopJam returns a JSON like this:

```
{
  "sessionToken" : "qwe.rty.uio",
  "kwsToken": "asd.fgh.jkl"
}
```

and KWS returns a JSON like this:

```
{
  "auth_token": "zxc.vbn.mkl",
  "type": "bearer",
  "exp": 829291921
}
```
clearly different JSONs that have to be mapped differently but both convey the same important information: namely that there is a JWT token that we need to later use to authenticate other requests. 

Then Protobufs can define:

```
protocol ILoggedUserModel {
   val token: String
}

protocol IAuthService {
   func login(username: String, password: String) -> ILoggedUserModel?
}
```

KWS and PopJam can then each have their own **implementations** of the `ILoggedUserModel` and `IAuthService` and still speak the same language to a 3rd party, the UI SDK.

**Pull request merged**
